### ISSUE TITLE
Not able to redirect to the application after successful login 

### ISSUE THREAD

**Issue by SameerChorge94** [gibahjoe/keycloak_flutter#11]
**Description:**

Hello,
I created the sample application as per your provided example, but facing some issues 
1. After running the project with the below command as redirectUrl needs the port no. 60000 as per server settings 
  `flutter run -d chrome --web-port 60000` 
project keeps redirect to another white screen and contains the below URL 
`http://localhost:60000/#error=login_required&state=cc4af115-8b2f-4a8e-a173-22adb54601f7`
it keeps showing the white screen then project screen alternatively

2. In above steps if we clicked the floating action button for login then it redirects to the  keycloak but after redirection instead of redirectin it keeps showing the white screen with URL containing the state and other information

Steps to reproduce:
1. Create new flutter project 
2. import packages as per the example and setup the whole example as it is in new project 
3. After running it keeps redirecting to the white blank screen with error code as per above and after clicking the login button in that interval it redirects to keycloak
4. but after successful login it does not redirected back to the app 

Versions:
```
Flutter 2.0.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (7 months ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```

we used the same package in another project also, but there it's not able to redirect to the keycloak on the login screen also
also the logs doesn't contain any errors

**Comment by gibahjoe** [comment]
HI. Can you provide a sample project with this issue let me take a look

**Comment by SameerChorge94** [comment]
[sample.zip](https://github.com/gibahjoe/keycloak_flutter/files/7287412/sample.zip)
Please find above example mention the keycloak Host and other details in main.dart file

**Comment by SathishManoj** [comment]
Any update on this bug. We are facing similar issue that is mentioned

**Comment by gibahjoe** [comment]
> [sample.zip](https://github.com/gibahjoe/keycloak_flutter/files/7287412/sample.zip)
> Please find above example mention the keycloak Host and other details in main.dart file

This sample works fine for me. I was able to login and it redirected me back to the application.

The only thing I changed were the keycloak url, realm and client ID

I use keycloak version 12.0.1

**Comment by gibahjoe** [comment]
> Any update on this bug. We are facing similar issue that is mentioned

Please what version of Keycloak are you on? and can you share a minimal sample that reproduces the issue?

**Comment by ms0713** [comment]
I am facing the same issue. 
I am using Keycloak Version 16.1.1.
Flutter Version 2.10.3

In Developer Tools, Network tab shows last network event as following
Headers:
Request URL: http://localhost:8080/auth/realms/flutter/protocol/openid-connect/login-status-iframe.html/init?client_id=flutter-demo-app&origin=http%3A%2F%2Flocalhost%3A61443
Request Method: GET
Status Code: 403 Forbidden
Remote Address: 127.0.0.1:8080
Referrer Policy: no-referrer

Payload:
client_id: flutter-demo-app
origin: http://localhost:61443

Kindly suggest the solution. I have implemented same code as provided by you.

**Comment by TMSantos** [comment]
it seems the library is not compatible with keycloak.js 16:

`Error: Exception: The user profile was not loaded as the user is not logged in.
    at Object.throw_ [as throw] (http://localhost:8030/dart_sdk.js:5063:11)
at keycloak_service.KeycloakService.new.loadUserProfile (http://localhost:8030/packages/keycloak_flutter/src/keycloak_service.dart.lib.js:171:21)
    at loadUserProfile.next (<anonymous>)
    at runBody (http://localhost:8030/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:8030/dart_sdk.js:40242:7)
at keycloak_service.KeycloakService.new.loadUserProfile (http://localhost:8030/packages/keycloak_flutter/src/keycloak_service.dart.lib.js:166:20)
at login_screen._LoginScreenState.new.<anonymous> (http://localhost:8030/packages/src/login/screen/login_screen.dart.lib.js:325:64)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:8030/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:8030/dart_sdk.js:40242:7)
at http://localhost:8030/packages/src/login/screen/login_screen.dart.lib.js:313:78
at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:8030/packages/flutter/src/scheduler/binding.dart.lib.js:728:9)
at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:8030/packages/flutter/src/scheduler/binding.dart.lib.js:704:37)
at http://localhost:8030/packages/flutter/src/scheduler/binding.dart.lib.js:609:14
    at internalCallback (http://localhost:8030/dart_sdk.js:26215:11)
Error: NoSuchMethodError: ''
Dynamic call with too few arguments. Expected: 1 Actual: 0
Receiver: Instance of '(KeycloakError) => Null'
Arguments: []
    at Object.throw_ [as throw] (http://localhost:8030/dart_sdk.js:5063:11)
    at Object.defaultNoSuchMethod (http://localhost:8030/dart_sdk.js:5497:15)
    at Function.noSuchMethod (http://localhost:8030/dart_sdk.js:6588:19)
    at Object.noSuchMethod (http://localhost:8030/dart_sdk.js:5494:30)
    at callNSM (http://localhost:8030/dart_sdk.js:5233:19)
    at Object._checkAndCall (http://localhost:8030/dart_sdk.js:5272:12)
    at Object.dcall (http://localhost:8030/dart_sdk.js:5275:17)
    at Keycloak.ret [as onAuthError] (http://localhost:8030/dart_sdk.js:61923:21)
    at XMLHttpRequest.req.onreadystatechange (_omitted_/auth/js/keycloak.js:794:50)`

**Comment by gibahjoe** [comment]
This issue has since been resolved. Kindly update to the latest version and create a new issue if it persists.
