### ISSUE TITLE
With your example I have Error: LateInitializationError: Field '_keycloakService' has not been initialized.

### ISSUE THREAD

**Issue by bernypack** [gibahjoe/keycloak_flutter#12]
Hi, 
I try your solution with the whole example project, my changes are only the KeycloakConfig informations with an https url.
Could you help me, I have theses errors : 
Error: LateInitializationError: Field '_keycloakService' has not been initialized.
    at Object.throw_ [as throw] (http://localhost:57290/dart_sdk.js:5061:11)
    at main._MyHomePageState.new.get [_keycloakService] (http://localhost:57290/packages/admin/main.dart.lib.js:259:37)
    at main._MyHomePageState.new.<anonymous> (http://localhost:57290/packages/admin/main.dart.lib.js:272:13)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:57290/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:57290/dart_sdk.js:38690:7)
    at http://localhost:57290/packages/admin/main.dart.lib.js:271:78
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:57290/packages/flutter/src/scheduler/binding.dart.lib.js:714:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:57290/packages/flutter/src/scheduler/binding.dart.lib.js:691:37)
    at http://localhost:57290/packages/flutter/src/scheduler/binding.dart.lib.js:600:14
    at internalCallback (http://localhost:57290/dart_sdk.js:25436:11)

And print into my web page : TypeError: dart.global.Keycloak is not a constructor

Thank you

**Comment by gibahjoe** [comment]
What version of flutter do you use? And also note that this library is for flutter web only

**Comment by NantEiPhyoThet** [comment]
Having the same error here.
`Flutter 2.6.0-11.0.pre • channel dev •
https://github.com/flutter/flutter.git
Framework • revision 4b330ddbed (3 months ago) • 2021-09-16 17:29:58
-0700
Engine • revision 5b81c6d615
Tools • Dart 2.15.0 (build 2.15.0-116.0.dev)```
