### ISSUE TITLE
User profile error

### ISSUE THREAD

**Issue by javshak** [gibahjoe/keycloak_flutter#7]
Hi - I have used the library for a Flutter web app I am building however I get the following error twice (details below). 
```
Error: Exception: The user profile was not loaded as the user is not logged in.
    at Object.throw_ [as throw] (http://localhost:4234/dart_sdk.js:5348:11)
    at keycloak_service.KeycloakService.new.loadUserProfile (http://localhost:4234/packages/keycloak_flutter/src/keycloak_service.dart.lib.js:190:21)
    at loadUserProfile.next (<anonymous>)
    at runBody (http://localhost:4234/dart_sdk.js:39211:34)
    at Object._async [as async] (http://localhost:4234/dart_sdk.js:39242:7)
    at keycloak_service.KeycloakService.new.loadUserProfile (http://localhost:4234/packages/keycloak_flutter/src/keycloak_service.dart.lib.js:185:20)
    at main._MyHomePageState.new.<anonymous> (http://localhost:4234/packages/flutter_app/main.dart.lib.js:613:64)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:4234/dart_sdk.js:39211:34)
    at Object._async [as async] (http://localhost:4234/dart_sdk.js:39242:7)
    at http://localhost:4234/packages/flutter_app/main.dart.lib.js:601:78
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:4234/packages/flutter/src/scheduler/binding.dart.lib.js:776:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:4234/packages/flutter/src/scheduler/binding.dart.lib.js:749:37)
    at http://localhost:4234/packages/flutter/src/scheduler/binding.dart.lib.js:653:14
    at internalCallback (http://localhost:4234/dart_sdk.js:25272:11)
```

I have used the main.dart file from the example you have provided - modified just the credentials. When my page loads I get the above error. Then on clicking the Login button I am redirected to the Keycloak server and after a successful login I am sent back to my app however this error shows up again.
Any advice?

**Comment by gibahjoe** [comment]
Hi, can you provide minimal reproducible code so that I can look into it

**Comment by javshak** [comment]
> Hi, can you provide minimal reproducible code so that I can look into it

Hey thanks for the reply! Regarding the code I have replicated the code from your 'example' project except for the following changes in the main.dart file ( Provider -> create () ).
No additional changes besides some text labels. I also downloaded your code (example) from github and ran it. I get the same error (posted previously) with no changes made. Same error when the main.dart is loaded.
            
```
            var keycloakService = KeycloakService(KeycloakConfig(
                url: 'https://ctisaas.com:9091/auth/', // Keycloak auth base url
                realm: 'master',
                clientId: 'jst'));
            keycloakService.keycloakEventsStream.listen((event) {
              if (event.type == KeycloakEventType.onAuthSuccess) {
                  print('the user is authenticated successfully!' );// User is authenticated
              }
```

**Comment by VenkatraghuB** [comment]
HI .....I also have same issue.
Redirection to keycloak works.
After entering credentials .....it is even redirecting to app
but app is not able to read or loaduserprofile


error from browser console

errors.dart:251 
        
       Uncaught (in promise) Error: Exception: The user profile was not loaded as the user is not logged in.
    at Object.throw_ [as throw] (:8080/dart_sdk.js:5067:11)
    at keycloak_service.KeycloakService.new.loadUserProfile (:8080/packages/keycloak_flutter/src/keycloak_service.dart.lib.js:171:21)
    at loadUserProfile.next (<anonymous>)
    at runBody (:8080/dart_sdk.js:40590:34)
    at Object._async [as async] (:8080/dart_sdk.js:40621:7)
    at keycloak_service.KeycloakService.new.loadUserProfile (:8080/packages/keycloak_flutter/src/keycloak_service.dart.lib.js:166:20)
    at main._MyHomePageState.new.<anonymous> (:8080/packages/example/main.dart.lib.js:306:64)
    at Generator.next (<anonymous>)
    at runBody (:8080/dart_sdk.js:40590:34)
    at Object._async [as async] (:8080/dart_sdk.js:40621:7)
    at :8080/packages/example/main.dart.lib.js:294:78
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (:8080/packages/flutter/src/scheduler/binding.dart.lib.js:722:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (:8080/packages/flutter/src/scheduler/binding.dart.lib.js:698:37)
    at :8080/packages/flutter/src/scheduler/binding.dart.lib.js:603:14
    at internalCallback (:8080/dart_sdk.js:26619:11)

**Comment by VenkatraghuB** [comment]
I think I found my problem .....issue is in keycloak client settings. I changed my client access type to public then it worked . This issue pops up when client access type is confidential.

**Comment by ms0713** [comment]
Hi @VenkatraghuB 
I have used the same code and I am having having the issue as you mentioned before.

Here is my error:

> Uncaught (in promise) Error: Exception: The user profile was not loaded as the user is not logged in.
>     at Object.throw_ [as throw] (errors.dart:251:49)
>     at keycloak_service.KeycloakService.new.loadUserProfile (keycloak_service.dart:87:7)
>     at loadUserProfile.next (<anonymous>)
>     at runBody (async_patch.dart:84:54)
>     at Object._async [as async] (async_patch.dart:123:5)
>     at keycloak_service.KeycloakService.new.loadUserProfile (keycloak_service.dart:81:45)
>     at main._MyHomePageState.new.<anonymous> (main.dart:97:49)
>     at Generator.next (<anonymous>)
>     at runBody (async_patch.dart:84:54)
>     at Object._async [as async] (async_patch.dart:123:5)
>     at main.dart:88:52
>     at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (binding.dart:1144:15)
>     at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (binding.dart:1089:9)
>     at binding.dart:862:7
>     at internalCallback (isolate_helper.dart:48:19)

I have checked with AccessType as "public" also but no success.

Here is my Keycloak settings.
![KeyCloakSettings](https://user-images.githubusercontent.com/12907055/162675095-b66304cb-009e-4661-a946-919094bec705.png)

What am I missing here?

**Comment by rsiva229** [comment]
Hi, 
Is there an update to the above mentioned issues? Even I'm facing issues while trying to loadUserProfile. If anyone can kindly post their solution here, that would be helpful. Thank you.
